## Preprocessing

In [30]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
df = pd.read_csv("../Resources/charity_data.csv")
df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [31]:
# df.describe()
# df['AFFILIATION'].nunique()

In [32]:
# # importing sweetviz
# import sweetviz as sv

# #analyzing the dataset
# charity_report = sv.analyze(df)
# #display the report
# charity_report.show_html('Charity.html')

In [33]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
df = df.drop("EIN", 1)
# df = df.drop("NAME", 1)
# df = df.drop("SPECIAL_CONSIDERATIONS",1)
# df = df.drop("STATUS",1)

/var/folders/08/k5qj0k9j1dbgppb_7vzc5rnm0000gn/T/ipykernel_11676/2688074749.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop("EIN", 1)

In [42]:
# Look at NAME value counts for binning
name_counts = df['NAME'].value_counts()
#  How many name counts are greater than 5?
name_counts[name_counts>5]

PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
OLD OAK CLIFF CONSERVATION LEAGUE INC                 6
AMERICAN NEPHROLOGY NURSES ASSOCIATION                6
HUMBLE ISD EDUCATIONAL SUPPORT GROUPS INC             6
PROFESSIONAL LOADMASTER ASSOCIATION                   6
CBMC INC                                              6
Name: NAME, Length: 354, dtype: int64

In [43]:
# Determine the number of unique values in each column.
name_counts.nunique()

92

In [35]:
# Determine which values to replace if counts are less than or equal to 5.
names_to_replace = list(name_counts[name_counts <= 5].index)

# Replace in dataframe
for app in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(app,"Other")
    
# Check to make sure binning was successful
application_df['NAME'].value_counts()

NameError: name 'name_counts' is not defined

In [36]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

NameError: name 'application_df' is not defined

In [5]:
# Determine the number of unique values in each column.
df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts for binning
df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
# Replace in dataframe

application_types_to_replace = ["T9","T13","T12","T2","T25","T14","T29","T15","T17"]
# application_types_to_replace = ["T9","T13","T12","T2","T25","T14","T29","T15","T17"]

for app in application_types_to_replace:
    df['APPLICATION_TYPE'] = df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# # Look at CLASSIFICATION value counts for binning
# classifications_val = df['CLASSIFICATION'].value_counts().values
# classifications_ind = df['CLASSIFICATION'].value_counts().index

In [9]:
# print(classifications_val)

In [10]:
# classifications_val[1]

In [11]:
# print(classifications_ind)

In [12]:
# len(classifications_ind)

In [13]:
# classification = []

# for i in range(0,71):
#         if classifications_val[i] < 1000:
#             k = classifications_ind[i]
#             classification.append(k)

In [14]:
# len(classification)

In [15]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE

In [16]:
df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [44]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

# len = len(classifications_val)

# classifications_val = df['CLASSIFICATION'].value_counts().values
# classifications_ind = df['CLASSIFICATION'].value_counts().index

# classifications_to_replace = []

# for i in range(0,71):
#         if classifications_val[i] < 1000:
#             k = classifications_ind[i]
#             classification.append(k)

# classifications_to_replace = classifications[(classifications < 1000)].index

class_df = df['CLASSIFICATION'].value_counts()

classifications_to_replace = class_df[(class_df < 100)].index

# Replace in dataframe
for cls in classifications_to_replace:
    df['CLASSIFICATION'] = df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [45]:
# import numpy as np
# df['ASK_AMT'] = np.log10(df['ASK_AMT'])

In [46]:
df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [47]:
# Convert categorical data to numeric with `pd.get_dummies`
df = pd.get_dummies(df,drop_first = True)

In [48]:
list(df)

['STATUS',
 'ASK_AMT',
 'IS_SUCCESSFUL',
 'NAME_100 BLACK MEN OF AMERICA',
 'NAME_100 BLACK MEN OF MEMPHIS INC',
 'NAME_100 BLACK MEN OF WEST GEORGIA INC',
 'NAME_1150 WEBSTER STREET INC',
 'NAME_116TH CAVALRY REGIMENT CHAPTER OF THE US CAVALRY & ARMOR ASSOCIATION',
 'NAME_13TH BOMB SQUADRON ASSOCIATION',
 'NAME_146TH ALUMNI ASSOCIATION',
 'NAME_14TH ARMORED DIVISION',
 'NAME_150TH INTELLIGENCE SQUADRON ENLISTED ADVISORY COUNCIL',
 'NAME_1632',
 'NAME_180 CHURCH',
 'NAME_180 YOUR GRIEF INC',
 'NAME_1930S GENERAL STORE MUSEUM',
 'NAME_1963 GIBBS ALUMNI INC',
 'NAME_1999 VEBA OF THE NONREPRESENTED EMPLOYEES OF SOUTHERN CA EDISON',
 'NAME_1K NATION INC',
 'NAME_2 B NON PROFIT CORPORATION',
 'NAME_2 X 2 INC',
 'NAME_2000 PROJECT SOCCER',
 'NAME_2041 FOUNDATION INCORPORATED',
 'NAME_21ST CENTURY HARVEST FOUNDATION',
 'NAME_21ST STREET FOUNDATION',
 'NAME_2618 COMMERCIAL DRIVE INVESTMENT GROUP LLC',
 'NAME_27TH DISTRICT AGRICULTURAL ASSOCIATION FRIENDS OF THE SHASTA',
 'NAME_2833 EXCHANGE CLUB OF BARTLETT TN',
 'NAME_29 PALMS FOOD FOR LIFE MINISTRY',
 'NAME_2C2SMILE INC',
 'NAME_2ND 2 NONE B TRAINING',
 'NAME_2ND CORINTHIANS OUTREACH MINISTRIES INC',
 'NAME_2ND IMAGE FOUNDATION INCORPORATED',
 'NAME_2STINKYFISH INC',
 'NAME_3 ANGELS MESSENGERS MOTORCYCLE ASSOCIATION',
 'NAME_300 SWIM TEAM INC',
 'NAME_360ARMOR INC',
 'NAME_3615 VFW AUXILIARY TO PARNELL-BURT POST',
 'NAME_361ST UNIT ADVISORY COUNCIL',
 'NAME_37TH JUDICIAL COURT APPOINTED SPECIAL ADVOCATES CASA',
 'NAME_3P FOUNDATION USA',
 'NAME_3RD OSS BOOSTER CLUB',
 'NAME_4 AG HAWAII INC',
 'NAME_4 AMERICAN DREAM INC',
 'NAME_4 CORNERS PROJECT INC',
 'NAME_4 H CLUBS & AFFILITATED 4 H',
 'NAME_4 HORSEMAN INVESTMENTS',
 'NAME_4 LEGGED RESCUE',
 'NAME_4 PAWS PANTRY',
 'NAME_4 R FRIENDS- RESCUE REHAB RE-HOME REACH OUT',
 'NAME_4 SQUARE INC - EDUCATIONAL',
 'NAME_4 VFW AUX TO DISTRICT DEPARTMENT OF OREGON',
 'NAME_4 WALLS INTERNATIONAL INCORPORATED',
 'NAME_4-H CLUBS & AFFILIATED 4-H ORGANIZATIONS',
 'NAME_4-H LEADERS FOUNDATION',
 'NAME_40 WASHINGTON TENT',
 'NAME_41 SOUTH VOLLEYBALL CLUB INC',
 'NAME_41131 TOMBALL LIONS CLUB',
 'NAME_42 SAMAJ OF GREATER KANSAS CITY INC',
 'NAME_425',
 'NAME_442 HRDC',
 'NAME_45-11 FOUNDATION INCORPORATED',
 'NAME_4963 AFT SALT LAKE COMMUNITY COLLEGE',
 'NAME_4GARRETT - GWH FOUNDATION',
 'NAME_4H HORSE SPECIALTY CLUB',
 'NAME_4LEGS4JUSTICE ANIMAL ADVOCATE AND RESCUE',
 'NAME_5 TALENTS MORE INC',
 'NAME_5-MINUTE NUCLEAR CORPORATION',
 'NAME_505 CHORUS',
 'NAME_5116 MAGAZINE STREET PREPARATORY HIGH SCHOOL',
 'NAME_5CS CHILD CARE CENTERS',
 'NAME_5TG INC',
 'NAME_647TH CIVIL ENGINEER SQUADRON BOOSTER CLUB',
 'NAME_6800 BELLAIRE PROJECT INC',
 'NAME_6TH SFS RATTLERS ASSOCIATION',
 'NAME_83 UNITED INDEPENDENT SUPPORTERS ASSOCIATION',
 'NAME_84 SLU MEDICINE SCHOLARSHIP PROGRAM',
 'NAME_9-11 MEMORIAL FIRE TRUCK',
 'NAME_911 PARK PLACE',
 'NAME_97TH PENNSYLVANIA VOLUNTEER INSANTRY COMPANY A',
 'NAME_9TH CAVALRY AND 25TH INFANTRY BUFFALO SOLDIERS OF LOUISIANA',
 'NAME_A & S RESEARCH A CALIFORNIA BUSINESS TR',
 'NAME_A AND M COMMUNITY DEVELOPMENT CORPORATION INC',
 'NAME_A BED OF MY OWN INC',
 'NAME_A BETTER BELIZE INC',
 'NAME_A BETTER DAI',
 'NAME_A BETTER SAN DIEGO ISSUES COMM A SPONSORED COMM OF SAN DIEGO AND',
 'NAME_A BETTER TASTE FOR OUR COMMUNITY',
 'NAME_A BIRTHDAY PARTY WISH INC',
 'NAME_A BRIGHT FURUTURE FOR KIDS',
 'NAME_A C I D A INC',
 'NAME_A C T I O N MINISTRY',
 'NAME_A CASE OF THE BLUES AND ALL THAT JAZZ',
 'NAME_A CATHOLIC JOURNEY OF FAITH',
 'NAME_A CENTER OF HOPE CPC INC',
 'NAME_A CHANCE FOR THERAPY INC',
 'NAME_A CHANCE INC',
 'NAME_A CHANCE TO SHINE INC',
 'NAME_A CHARITY CHALLENGE INC',
 'NAME_A CHILDRENS THEATRE OF THE MESILLA VALLEY INC',
 'NAME_A COMMUNITY PREGNANCY CENTER',
 'NAME_A COURSE IN MIRACLES CENTER INC',
 'NAME_A CUP OF COLD WATER',
 'NAME_A DAY IN THE LIFE PROJECT INC',
 'NAME_A DIAMOND IN THE RUFF INCORPORATED',
 'NAME_A DOBERMAN ADOPTION PLACEMENT TEAM',
 'NAME_A DOLLAR TODAY INC',
 'NAME_A F T E R INC',
 'NAME_A GIRLS PROMISE INCORPORATED',
 'NAME_A HAND UP -- NOT A HAND-OUT',
 'NAME_A HERO WAS HERE SGT JOHN KYLE DAGGETT FOUNDATION',
 'NAME_A HOUSE OF THE LIVING GOD CHURCH OF JESUS CHRIST COJC INC',
 'NAME_A HUMANITARIAN ORGANIZATION PROMOTING EDUCATION',
 'NAME_A J MOUNTED RANGERS',
 'NAME_A L S OF MIDDLE TENNESSEE',
 'NAME_A LIFE WORTH LIVING',
 'NAME_A LIFES WISH INC',
 'NAME_A LOUD & CLEAR CALL MINISTRY',
 'NAME_A M B A INC',
 'NAME_A MILLION MATTERS INC',
 'NAME_A MOTHERS MERCY THE SRC STORY',
 'NAME_A MOTHERS TOUCH EDUCATION AND CARE CENTER',
 'NAME_A MOUNTAIN COMMUNITY INCORPORATED',
 'NAME_A NEW BEGINNING INC',
 'NAME_A NEW DAY VOCATIONAL PROGRAM',
 'NAME_A NEW FOCUS',
 'NAME_A PROMISED LAND ANIMAL RESCUE INC',
 'NAME_A SAFE PLACE COMMUNITY DEVELOPMENT CORPORATION',
 'NAME_A SHEPHERDS LIFE 7 INC',
 'NAME_A SOLUTION THROUGH TREATMENT',
 'NAME_A TENDER LOVE AND CARE INC',
 'NAME_A THEATRE NEAR U INC',
 'NAME_A TIME FOR MERCY',
 'NAME_A TU SALUD INC',
 'NAME_A TUTORING PLACE',
 'NAME_A VISION FOR WILMINGTON MINISTRIES',
 'NAME_A VOICE IN THE WILDERNESS EMPOWERMENT CENTER',
 'NAME_A WOMANS PLACE INC',
 'NAME_A WOMENS PREGNANCY CENTER',
 'NAME_A WOMENS PREGNANCY CENTER OF MADISON INC',
 'NAME_A WORD FOR THE TIMES INC',
 'NAME_A WORLD AWARE INC',
 'NAME_A WORLD FOR CHILDREN',
 'NAME_A WORLD INSTITUTE FOR A SUSTAINABLE HUMANITY - HELLAS - MESOGEIOU',
 'NAME_A-FIB INC',
 'NAME_AABY FOUNDATION',
 'NAME_AACE INTERNATIONAL',
 'NAME_AADF LEGACY AIRBASE INC',
 'NAME_AAMA STATE OF OREGON SOCIETY LINN- BENTON CHAPTER',
 'NAME_AAP CALIFORNIA CHAPTER 1 FOUNDATION',
 'NAME_AARON BERINDA INTERNATIONAL MINISTRY INC',
 'NAME_AARON KEITH ROBINSON FOUNDATION INC',
 'NAME_AARON MAHLON ARTS & FRAMING',
 'NAME_AAUW COLVILE BRANCH',
 'NAME_AAUW TARRANT COUNTY BRANCH',
 'NAME_AAVI INC',
 'NAME_AAY HOME INCARCERATION TO COMMUNITY',
 'NAME_ABANDONED BABIES CHRISTIAN MINISTRIES',
 'NAME_ABANDONED CAT TEAM',
 'NAME_ABATE MOTORCYCLE SAFETY EDUCATION PROGRAM',
 'NAME_ABATE OF COLORADO',
 'NAME_ABBA AGAPE CHURCH',
 'NAME_ABBA FATHER MINISTRIES',
 'NAME_ABBEY RHF HOUSING INC',
 'NAME_ABBIES ANGELS',
 'NAME_ABC INFANTS INC',
 'NAME_ABC OF SOUTHERN CALIFORNIA BENEFIT TRUST FUND',
 'NAME_ABC WORKFORCE DEVELOPMENT FOUNDATION',
 'NAME_ABIDE154 INC',
 'NAME_ABIDING IN HIS PRESENCE MINISTRIES',
 'NAME_ABIDING IN THE VINE',
 'NAME_ABIDING SOLUTIONS INTERNATIONAL MINISTRIES INCORPORATED',
 'NAME_ABILENE CLEAN AND PROUD INC',
 'NAME_ABILENE JUBILEE HOUSE INC',
 'NAME_ABLE',
 'NAME_ABLE COMMUNITY INC',
 'NAME_ABODE COMMUNITY HOUSING',
 'NAME_ABOGAR INTERNATIONAL MINISTRIES',
 'NAME_ABOOUT FACE INC',
 'NAME_ABOUT SOCCER INC',
 'NAME_ABOUT-FACE MEDIA LITERACY INC',
 'NAME_ABOVE ALL SPORTS',
 'NAME_ABOVE AVERAGE LEARNING CENTERS',
 'NAME_ABOVE THE SEAS LLC',
 'NAME_ABRAHAM FOUNDATION INC',
 'NAME_ABRAHAM LINCOLN ELEMENTARY BOOSTER CLUB',
 'NAME_ABRAHAM LINCOLN HS BROOKLYN NY FLORIDA ALUMNI ASSOCIATION INC',
 'NAME_ABRAZO FOSTER FAMILY AGENCY',
 'NAME_ABUNDANCE ACADEMY',
 'NAME_ABUNDANCE FOR LIFE',
 'NAME_ABUNDANT LIFE FOR ALL MINISTRIES WORLDWIDE INC',
 'NAME_ABUNDANT LIVING COMMUNITY ORGANIZATION INC',
 'NAME_ABUSE RECOVERY MINISTRY & SERVICES',
 'NAME_ABUSIVE DELIVERANCE IN PROGRESS INC',
 'NAME_ACACIA FRATERNITY INCORPORATED',
 'NAME_ACADEMIA DE LES LLETRES I BELLES ARTS',
 'NAME_ACADEMIC AND COMMUNITY EXCELLENCE INCORPORATED',
 'NAME_ACADEMIC EDGE FOR GIRLS IN SPORTS FOUNDATION',
 'NAME_ACADEMIC INFROMER INC',
 'NAME_ACADEMIC SCIENCE AND TECHNOLOGY CENTER INC',
 'NAME_ACADEMICS PLUS CHARTER SCHOOL PARENT TEACHER ORGANIZATION INC',
 'NAME_ACADEMIES OF OXFORD PREP',
 'NAME_ACADEMY ADVISORY BOARD INC',
 'NAME_ACADEMY FOR CERTIFICATION OF VISION REHABILITATION & EDUCATION PROFES',
 'NAME_ACADEMY FUNDING OF BASTROP',
 'NAME_ACADEMY GLOBAL LEARNING',
 'NAME_ACADEMY MASTERS SWIM TEAM',
 'NAME_ACADEMY OF CALIFORNIA ELITE SOCCER INC',
 'NAME_ACADEMY OF CHINESE PERFORMING ARTS FOUNDATION',
 'NAME_ACADEMY OF COMMUNITY THEATRE',
 'NAME_ACADEMY OF GENERAL DENTISTRY',
 'NAME_ACADEMY OF MANAGED CARE PHARMACY',
 'NAME_ACADEMY OF TRANSDISCIPLINARY LEARNING AND ADVANCED STUDIES INC',
 'NAME_ACADEMY PARENT CLUB',
 'NAME_ACADIANA CHAPTER OF THE CONSTRUCTION SPECIFICATIONS',
 'NAME_ACADIANA CUP FOUNDATION',
 'NAME_ACADIANA DIAPER DEPOT INC',
 'NAME_ACADIANA DOWN SYNDROME ASSOCIATION',
 'NAME_ACADIANA GOOD TIMES ROLLERS',
 'NAME_ACADIANA PRIDE FESTIVAL',
 'NAME_ACC HOPE AZ',
 'NAME_ACCCOLPH INC',
 'NAME_ACCELERATION TRANSPORTATION RATE BUREAU INC',
 'NAME_ACCELLERA ORGANIZATION',
 'NAME_ACCEPTING CHALLENGES TO IMPROVE OUR NATION - COMMUNITY DEVLOPMENT CORP',
 'NAME_ACCESS CENTER INC',
 'NAME_ACCESS CONNECTIONS TO SUCCESS INC',
 'NAME_ACCESS FOR CHANGE COMMUNITY DEVELOPMENT CORPORATION',
 'NAME_ACCESS INSTITUTE',
 'NAME_ACCESS TO EDUCATION EMPOWERMENT ECONOMIC DEVELOPMENT CORPORATION',
 'NAME_ACCESSIBILITY INC',
 'NAME_ACCOMPANIED BY GODS LOVE',
 'NAME_ACCORD INC',
 'NAME_ACCORD MINISTRIES INC',
 'NAME_ACCOUNTABILITY PROJECT LLC',
 'NAME_ACCOUNTING AND FINANCIAL WOMENS ALLIANCE',
 'NAME_ACE EDUCATION INTERNATIONAL INC',
 'NAME_ACE ENTERPRISES',
 'NAME_ACE MENTOR PROGRAM OF AMERICA INC',
 'NAME_ACEC TAX EXEMPT LIFE-HEALTH INS TR',
 'NAME_ACF WESTERN USA INC',
 'NAME_ACF-SMOKY MOUNTAIN CHAPTER',
 'NAME_ACHIEVE COMMUNITY DEVELOPMENT CORPORATION',
 'NAME_ACHIEVE FORT BEND COUNTY',
 'NAME_ACHIEVEMENT REWARDS FOR COLLEGE SCIENTISTS FOUNDATION INC OREGON',
 'NAME_ACHIEVEMENT REWARDS FOR COLLEGE SCIENTISTS FOUNDATION INC TAMPA BA',
 'NAME_ACHIEVING LEADERSHIP INSTITUTE',
 'NAME_ACHILLES DIVERS INC',
 'NAME_ACI ALASKA CHAPTER',
 'NAME_ACINN CORPORATION',
 'NAME_ACIREMAS CREATIONS',
 'NAME_ACLU FOUNDATION OF TEXAS INC',
 'NAME_ACME FOUNDATION SRI THYAGARAJA MUSIC FESTIVAL',
 'NAME_ACONA COMMUNITY OUTREACH',
 'NAME_ACORN COMMUNITY LAND ASSOCIATION OF LA',
 'NAME_ACRES OF DIAMONDS',
 'NAME_ACSC INCORPORATED',
 'NAME_ACT FOR A CAUSE INC',
 'NAME_ACTION',
 'NAME_ACTION COMMUNICATION AND EDUCATION REFORM',
 'NAME_ACTION COUNCIL FOR 29 PALMS INC',
 'NAME_ACTION UNITED FOR ENTERTAINERS AND DIVERSE ARTIST',
 'NAME_ACTIONN',
 'NAME_ACTIVE 20-30 CLUB OF SACRAMENTO NO 1',
 'NAME_ACTIVE 20-30 UNITED STATES AND CANADA',
 'NAME_ACTIVE FAMILY SERVICES',
 'NAME_ACTIVE SINGLE CHRISTIAN SCIENTISTS ASSOCIATION',
 'NAME_ACTIVE YOUTH AGAINST OBESITY',
 'NAME_ACTIVELY VISITING ORPHANS WIDOWS ELDERLY AND DISABLED INC',
 'NAME_ACTORS COMPANY AND THEATER SCHOOL',
 'NAME_ACTS MINISTRY',
 'NAME_ACTS MISSIONS',
 'NAME_ACTS OF HOPE INC',
 'NAME_ACTS4 COMMUNITY OUTREACH SERVICESINC',
 'NAME_ACU ANGELS',
 'NAME_ACUAVITA FOUNDATION INC',
 'NAME_ACUSN-THE ARIZONA COLLEGE AND UNIVERSITY STUDENT NETWORK',
 'NAME_ACWORTH ART CENTER',
 'NAME_AD ASTRA AREA AQUATICS BOOSTER ASSOCIATION',
 'NAME_AD FONTES',
 'NAME_ADA COUNTY PARAMEDIC ASSOCIATION',
 'NAME_ADA MBAISE USA INC',
 'NAME_ADAIR EVANGELISTIC MINISTRIES INC',
 'NAME_ADAM AND BRUCE HOUSING CORPORATION',
 'NAME_ADAM MORGAN FOUNDATION',
 'NAME_ADAM TULSA ENERGY NETWORK',
 'NAME_ADAMO & CO LLC',
 'NAME_ADAMS CAPE MEDICAL FUND INC',
 'NAME_ADAMS COUNTY YOUTH INITIATIVE INC',
 'NAME_ADAMS PROJECT INC',
 'NAME_ADAMSVILLE ELEM PTA',
 'NAME_ADAPTABLE SECURITY CORP',
 'NAME_ADAPTIVE COMPUTER TRAINING INC',
 'NAME_ADDICTION COUNSELING AND EDUCATION SERVICES INC',
 'NAME_ADDICTION PROFESSIONALS ASSOCIATION FOR CALIFORNIA',
 'NAME_ADDIE MAE LYNCH TR FBO THE BUTLER FAMILY CEMETERY',
 'NAME_ADDISON ANONYMOUS GROUP CLUB',
 'NAME_ADINKRA NOLA',
 'NAME_ADIRONDACK 46R CONSERVATION TR',
 'NAME_ADOG INC',
 'NAME_ADOLESCENT TREATMENT CENTERS INC',
 'NAME_ADOPT A GOLDEN BIRMINGHAM INC',
 'NAME_ADOPT RESCUE DOGS',
 'NAME_ADOPT SHELTER ANIMAL PETS - WEST RICHLAND',
 'NAME_ADOPT-A-BIKE INCORPORATED',
 'NAME_ADOSH MEMORIAL TR',
 'NAME_ADP TOTALSOURCE INC HEALTH ANDWELFARE PLAN TRUST',
 'NAME_ADRIENNE CASE MCDOWELL FOUNDATION',
 'NAME_ADSI',
 'NAME_ADULT & CHILDREN NUTRITION SERVICES INC',
 'NAME_ADULT BASIC EDUCATION COUNCIL OF LAUDERDALE COUNTY TENNESSEE-ABE-',
 'NAME_ADULT CONGENITAL HEARTS OF GREATER ATLANTA',
 'NAME_ADULT FOSTER HOMECARE ASSOCIATION FOUNDATION OF HAWAII',
 'NAME_ADULT FOSTER HOMECARE ASSOCIATIONOF HAWAII',
 'NAME_ADULT LEARNING CENTER',
 'NAME_ADULTS AND YOUTH UNITED DEVELOPMENT ASSOCIATION INC',
 'NAME_ADULTS MANKIND ORGANIZATION INC',
 'NAME_ADVANCE K9 SEARCH AND RECOVERY INC',
 'NAME_ADVANCE PRODUCTIONS OF THOMAS CREEK RETREAT',
 'NAME_ADVANCECAMP INC',
 'NAME_ADVANCED MEDICAL HEALTH CENTER LLC',
 'NAME_ADVANCED PLACEMENT EDUCATIONAL INSTITUTE',
 'NAME_ADVANCED THERAPIES INCORPORATED',
 'NAME_ADVANCEMENT THROUGH OPPORTUNITY AND KNOWLEDGE INCORPORATED',
 'NAME_ADVANCING COMMUNITIES FOUNDATION',
 'NAME_ADVANCING STEM FOR STUDENTS IN SOUTH TEXAS',
 'NAME_ADVANTAGE FLAG FOOTBALL',
 'NAME_ADVANTAGE NOLA TENNIS ASSOCIATION',
 'NAME_ADVANTAGE SPORTS ACADEMY LLC',
 'NAME_ADVENT OPENDOOR MINISTRIES A CALIFORNIA RELIGIOUS CORPORATION',
 'NAME_ADVENTIST IHIE HIGH SCHOOL OLDSTUDENTS ASSOCIATION OF AMERICA INC',
 'NAME_ADVENTIST INTERNATIONAL EYE SERVICES',
 'NAME_ADVENTIST MEDICAL EVANGELISM NETWORK MEDIA INC',
 'NAME_ADVENTIST VIRTUAL LEARNING NETWORK',
 'NAME_ADVENTURE ACCESS GROUP INC',
 'NAME_ADVENTURES IN ENGINEERING INC',
 'NAME_ADVENTURES WITH JESUS MINISTRIES WITH JOHN MILLER',
 'NAME_ADVISSORY COMMISSION ON TEXTBOOK SPECIFICATIONS INC',
 'NAME_ADVOCACY RESOURCE CENTER INC',
 'NAME_ADVOCAT TNR GROUP',
 'NAME_ADVOCATES AGAINST DOMESTIC VIOLENCE IN THE AFRICAN AMERICAN COMMUNITY',
 'NAME_ADVOCATES BELIEVING IN LIVING EMPOWERED',
 'NAME_ADVOCATES FOR ACADEMIC EXCELLENCE IN EDUCATION INC',
 'NAME_ADVOCATES FOR COMMUNITY CHOICE',
 'NAME_ADVOCATES FOR HEALTHY COMMUNITIES INC',
 'NAME_ADVOCATES FOR LATINO ARTS & CULTURE CONSORTIUM INC',
 'NAME_ADVOCATES FOR SUSTAINABLE ANIMAL POPULATIONS',
 'NAME_ADVOCATES FOR THE OAK RIDGE RESERVATION',
 'NAME_ADVOCATES FOR VICTIMS OF ABUSE',
 'NAME_ADVOCATES FOR VICTIMS OF IMPAIRED DRIVING',
 'NAME_ADVOCATES OF PLANNED PARENTHOOD OF THE ST LOUIS REGION & SOUTHWEST MO',
 'NAME_AEALAS INC',
 'NAME_AEMP EDUCATION FOUNDATION',
 'NAME_AEQUALIS INC',
 'NAME_AERO INSTITUTE',
 'NAME_AERONAUTICS EDUCATION ENTERPRISES',
 'NAME_AEROSPACE CONTRACTORS TR',
 'NAME_AEROSPACE LEGACY ENGINEERING AND TECHNOLOGY RECOVERY ORGANIZATION',
 'NAME_AESOP INC',
 'NAME_AESTHETIC SURGERY EDUCATION & RESEARCH FOUNDATION',
 'NAME_AESTHETICIANS OF THE NORTHWEST',
 'NAME_AF SELECT BASEBALL PEARLAND',
 'NAME_AF WINGMOMS',
 'NAME_AF WOMENS CYCLING CLUB',
 'NAME_AFABWORLD',
 'NAME_AFAST INC',
 'NAME_AFC EMPLOYEE ALLIANCE',
 'NAME_AFCEA EDUCATIONAL FOUNDATION',
 'NAME_AFENMAI WORLD CONGRESS INC',
 'NAME_AFFECT CHANGE',
 'NAME_AFFILIATED INTERNATIONAL MINISTRIES',
 'NAME_AFFIRMATION CENTER FOR THOUGHT INC',
 'NAME_AFFIRMATIVE CONSENT PROJECT INC',
 'NAME_AFFORDABLE HOUSING AND ECONOMIC DEVELOPMENT FOUNDATION',
 'NAME_AFFORDABLE HOUSING PROVIDERS OF AMERICA',
 'NAME_AFGE LOCAL 1711',
 'NAME_AFGE NAVY SOUTHEAST COUNCIL AFL CIO C-243',
 'NAME_AFGHANS4TOMORROW INC',
 'NAME_AFM MINISTRY INC',
 'NAME_AFRICA BOUND CORPORATION',
 'NAME_AFRICA NEEDS COMMUNITY DEVELOPMENT DEPARTMENT',
 'NAME_AFRICA RENEWAL MINISTRIES INC',
 'NAME_AFRICAN AMERICAN BUSINESS LEADERSHIP COUNCIL INC',
 'NAME_AFRICAN AMERICAN CLUB OF WEST PASCO COUNTY INC',
 'NAME_AFRICAN AMERICAN DANCE REVIEW',
 'NAME_AFRICAN AMERICAN EXPERIENCE MUSEUM INC',
 'NAME_AFRICAN AMERICAN MUTUAL SUPPORT ASSOCIATES INC',
 'NAME_AFRICAN AMERICAN REACH & TEACH HEALTH MINISTRY',
 'NAME_AFRICAN AMERICAN WELLNESS PROJECT',
 'NAME_AFRICAN AMERICAN WOMEN UNITED AAWU',
 'NAME_AFRICAN AMERICAN YOUTH LEADERSHIP CONFERENCE',
 'NAME_AFRICAN CARIBBEAN AMERICAN PERFORMING ARTISTS INC',
 'NAME_AFRICAN GIRL EQUITY INC',
 'NAME_AFRICAN GROVE INSTITUTE FOR THE ARTS CENTRAL TEXAS CHAPTER',
 'NAME_AFRICAN MINISTRIES INTERNATIONAL',
 'NAME_AFRICAN POLICY AND APPLIED RESEARCH INSTITUTE',
 'NAME_AFRICAN SOCIAL AND IMMIGRATION SERVICES',
 'NAME_AFRICAN STRATEGIC LEADERSHIP PRAYER NETWORK',
 'NAME_AFRICAN UNION OF NORTHERN NEVADA CHARITIES',
 'NAME_AFRICAN-AMERICAN MALE ACHIEVERS NETWORK',
 'NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS',
 'NAME_AFRIKAN CENTERED EDUCATION TASKFORCE INC',
 'NAME_AFRIKAN CULTURAL RESEARCH AND STUDY GROUP OF LONG BEACH',
 'NAME_AFSCME LOCAL 2076 ORANGE COUNTY BENEFITS TRUST',
 'NAME_AFTER GODS HEART INC',
 'NAME_AFTV FIVE',
 'NAME_AGAINST ALL ODDS ALL BREED RESCUE',
 'NAME_AGAINST ALL ODDS MINISTRIES',
 'NAME_AGAINST HIV AIDS INC',
 'NAME_AGAINST THE ODDS MENTORING SERVICES',
 'NAME_AGAPE 4 ORPHANS INTERNATIONAL INC',
 'NAME_AGAPE CHARITY HOUSE FOR KIDS',
 'NAME_AGAPE CHILDRENS EMERGENCY SHELTER HOUSTON',
 'NAME_AGAPE CHILDRENS MUSEUM',
 'NAME_AGAPE CLINIC INC',
 'NAME_AGAPE EDUCATIONAL MEDIA INC',
 'NAME_AGAPE ENTERPRISES FOUNDATION INC',
 'NAME_AGAPE FOOD PANTRY OF TAYLOR INC',
 'NAME_AGAPE MINISTRIES GLOBAL',
 'NAME_AGAPE WORLD CHRISTIAN MINISTRIES AND TRAINING CENTER',
 'NAME_AGBEYOMI WORLD OUTREACH INC',
 'NAME_AGE TO AGE INC',
 'NAME_AGENCY FOR HOLISTIC EVANGELISM AND DEVELOPMENT INC',
 'NAME_AGENTS ASSOCIATION',
 'NAME_AGGIELAND PETS WITH A PURPOSE',
 'NAME_AGING EAGLES CLUB INC',
 'NAME_AGING IN PLACE - THE WOODLANDS',
 'NAME_AGNES BRINKLUM TR UW 05181933',
 'NAME_AGOFI OF USA',
 'NAME_AGRICULTURE IMPLEMENTATION RESEARCH & EDUCATION',
 'NAME_AHAVATH ACHIM CONGREGATION ENDOWMENT FUND INC',
 'NAME_AHEAD INC',
 'NAME_AHED INTERNATIONAL INC',
 'NAME_AHH',
 'NAME_AHISKA-TURKISH COMMUNITY CENTER OF ATLANTA INC',
 'NAME_AHTANUM MISSION COUNCIL NO 6097 KNIGHTS OF COLUMBUS',
 'NAME_AHUAS CLINIC FOUNDATION',
 'NAME_AHUIMANU OHANA INCORPORATED',
 'NAME_AID AFRICA',
 'NAME_AID TO ABUSED WOMEN',
 'NAME_AIDEN MARLEY HUGHES FOUNDATION INC',
 'NAME_AIDING SHELTER ANIMALS PROJECT',
 'NAME_AIDS TASKFORCE OF GREATER CLEVELAND INC',
 'NAME_AIESEC ALUMNI IBEROAMERICA CORP',
 'NAME_AIKI INTEGRATED ARTS',
 'NAME_AIKIDO ACADEMY OF DENTON',
 'NAME_AIKIDO DOJOS OF SAN ANTONIO',
 'NAME_AIM AND FOCUS FOUNDATION',
 'NAME_AIM HIGHER IN EDUCATION INCORPORATED',
 'NAME_AIMUSIC SCHOOL',
 'NAME_AIR & WASTE MANAGEMENT ASSOCIATION GULF COAST CHAPTER',
 'NAME_AIR ALLIANCE HOUSTON',
 'NAME_AIR AND WASTE MANAGEMENT ASSOCIATION GRAND CANYON SECTION',
 'NAME_AIR FORCE ASSOCIATION',
 'NAME_AIR FORCE ASSOICATION',
 'NAME_AIR FORCE VILLAGES INC',
 'NAME_AIR WARRIOR COURAGE FOUNDATION',
 'NAME_AIREDALE TERRIER CLUB OF AMERICA CHARITABLE TR',
 'NAME_AIRPORT ASSISTANCE CENTER INC',
 'NAME_AIRPORT ROTARY FOUNDATION',
 'NAME_AJS FOUNDATION INC',
 'NAME_AKAKA SCHOLARS FOUNDATION',
 'NAME_AKILAH CHAPTER 122',
 'NAME_AKITA ADVOCATES RELOCATION TEAM ARIZONA',
 'NAME_AKWA IBOM STATE ASSOCIATION - OREGON & WASHINGTON',
 'NAME_AL-RAHMAN FOUNDATION WAQF',
 'NAME_AL-SHIFA CLINIC INC',
 'NAME_ALABAMA ALLIANCE FOR CHRISTIAN EDUCATION INC',
 'NAME_ALABAMA ANIMAL CONTROL OFFICERS STANDARDS AND TRAINING COMMISSION',
 'NAME_ALABAMA ASSOCIATION FOR PARENTS OF CHILDREN WITH VISUAL IMPAIRMENTS',
 'NAME_ALABAMA ASSOCIATION FOR PLAY THERAPY',
 'NAME_ALABAMA ASSOCIATION OF FEDERAL EDUCATION PROGRAM ADMINISTRATORS',
 'NAME_ALABAMA ASSOCIATION OF WOMENS CLUBS INC',
 'NAME_ALABAMA BEAUTY SALON CO-OP CENTER INC',
 'NAME_ALABAMA BETA CHAPTER OF THE SIGMA PHI EPSILON FRATERNITY',
 'NAME_ALABAMA BICYCLE COALITION',
 'NAME_ALABAMA CHRISTIAN UNITED APPEAL FUND INC',
 'NAME_ALABAMA COMMUNITY CARE - REGION A INC',
 'NAME_ALABAMA COUNCIL FOR ADMIN & SPECIAL ED INC',
 'NAME_ALABAMA EDGE',
 'NAME_ALABAMA FAMILY CHILD CARE ASSOCIATION',
 'NAME_ALABAMA FEDERATION OF WOMENS CLUBS',
 'NAME_ALABAMA FOOD BANK ASSOCIATION INC',
 'NAME_ALABAMA GREYHOUND RESCUE AND ADOPTION CENTER',
 'NAME_ALABAMA HEALTHCARE CONSORTIUM LLC',
 'NAME_ALABAMA INDIA TRADE DEVELOPMENT',
 'NAME_ALABAMA KINDERGARDEN CONFERENCE INC',
 'NAME_ALABAMA LATIN AMERICAN ASSOCIATION',
 'NAME_ALABAMA LEAGUE FOR NURSING',
 'NAME_ALABAMA NONPROFIT EATING DISORDERSASSISTANCE FOUNDATION',
 'NAME_ALABAMA OPTOMETRIC ASSOCIATION',
 'NAME_ALABAMA POWER SERVICE ORGANIZATION INC',
 'NAME_ALABAMA REGION S C C A',
 'NAME_ALABAMA RIVER REGION BALLET SCHOOL AND YOUTH COMPANY',

In [49]:
# Split our preprocessed data into our features and target arrays
X = df.drop('IS_SUCCESSFUL',axis=1)
y = df['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [50]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [51]:
inputs = len(X.columns)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=9, activation="relu", input_dim=inputs))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=9, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

In [52]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=12, activation="tanh", input_dim=inputs))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=12, activation="tanh"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=6, activation="tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_4 (Dense)              (None, 12)                235416
_________________________________________________________________
dense_5 (Dense)              (None, 12)                156
_________________________________________________________________
dense_6 (Dense)              (None, 6)                 78
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 7
=================================================================
Total params: 235,657
Trainable params: 235,657
Non-trainable params: 0
_________________________________________________________________

In [53]:
# EVALUATE 1ST PASS

In [54]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [55]:
from keras.callbacks import Callback

mc = tf.keras.callbacks.ModelCheckpoint('weights{epoch:08d}.h5',save_weights_only=True, period=5)

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, callbacks=[mc], epochs=10)

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
Epoch 1/10

2022-03-27 21:52:46.260480: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.

804/804 [==============================] - 8s 10ms/step - loss: 0.5211 - accuracy: 0.7364
Epoch 2/10
804/804 [==============================] - 8s 10ms/step - loss: 0.1627 - accuracy: 0.9453
Epoch 3/10
804/804 [==============================] - 8s 10ms/step - loss: 0.1074 - accuracy: 0.9612
Epoch 4/10
804/804 [==============================] - 8s 10ms/step - loss: 0.1002 - accuracy: 0.9630
Epoch 5/10
804/804 [==============================] - 8s 10ms/step - loss: 0.0963 - accuracy: 0.9626
Epoch 6/10
804/804 [==============================] - 8s 10ms/step - loss: 0.0945 - accuracy: 0.9634
Epoch 7/10
804/804 [==============================] - 8s 10ms/step - loss: 0.0921 - accuracy: 0.9636
Epoch 8/10
804/804 [==============================] - 8s 10ms/step - loss: 0.0915 - accuracy: 0.9636
Epoch 9/10
804/804 [==============================] - 8s 10ms/step - loss: 0.0908 - accuracy: 0.9631
Epoch 10/10
804/804 [==============================] - 8s 10ms/step - loss: 0.0895 - accuracy: 0.9639

In [58]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 2s - loss: 0.5148 - accuracy: 0.7202
Loss: 0.5147528648376465, Accuracy: 0.7202332019805908

In [57]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

In [ ]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh'])
    
    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=6,
        max_value=18,
        step=6), activation=activation, input_dim=inputs))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 2)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=6,
            max_value=12,
            step=6),
            activation=activation))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [ ]:
# Import the kerastuner library
import kerastuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=10,
    hyperband_iterations=2)

In [ ]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

In [ ]:
# Evaluate best model against full test data
best_model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
# Get top 3 model hyperparameters and print the values
top_hyper = tuner.get_best_hyperparameters(3)
for param in top_hyper:
    print(param.values)